'use client';

import React from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import { useAuthController } from '@/frontend/view/controllers/useAuthController';
import { Loading } from '@/frontend/view/components/Loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { isLoading } = useAuthController();

  return (
    <html lang="pt-BR" className="h-full">
      <body className={`${inter.className} h-full text-gray-900`}>
        {isLoading ? (<Loading />) : children}
      </body>
    </html>
  );
}
